pipeline:
  name: Sample_Maven_Build
  identifier: Sample_Maven_Build
  projectIdentifier: ci_cd_yuvaraj_k
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Yuvaraj_K
        build: <+input>
  stages:
    - stage:
        name: Maven
        identifier: Maven
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: mvn clean install
